// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5MF4ez4IvW4kicPwmzb_RIqlvyBkADo',
    appId: '1:297433248246:web:4c49a801164b90938517d7',
    messagingSenderId: '297433248246',
    projectId: 'breakaway-f7405',
    authDomain: 'breakaway-f7405.firebaseapp.com',
    storageBucket: 'breakaway-f7405.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC939_SlPFoQx_z59Xh3zVmL8Pu7Ux4QKU',
    appId: '1:297433248246:android:0d55648184a1f1748517d7',
    messagingSenderId: '297433248246',
    projectId: 'breakaway-f7405',
    storageBucket: 'breakaway-f7405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoNAIjlbepZJclwG6sgHUY8itxYzmnu8',
    appId: '1:297433248246:ios:c60250fe2bd6b66d8517d7',
    messagingSenderId: '297433248246',
    projectId: 'breakaway-f7405',
    storageBucket: 'breakaway-f7405.appspot.com',
    iosBundleId: 'com.example.breakaway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoNAIjlbepZJclwG6sgHUY8itxYzmnu8',
    appId: '1:297433248246:ios:20a8ecc8ca7b5e098517d7',
    messagingSenderId: '297433248246',
    projectId: 'breakaway-f7405',
    storageBucket: 'breakaway-f7405.appspot.com',
    iosBundleId: 'com.example.breakaway.RunnerTests',
  );
}
